name: nodejs
description: 'Node.js application'
displayName: Node.js Runtime
icon: https://nodejs.org/static/images/logos/nodejs-new-pantone-black.svg
versions:
  - version: 2.1.1
  - version: 2.2.0
  - version: 3.0.0
    default: true # should have one and only one default version
