#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Check registry build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout registry build tools
      uses: actions/checkout@v2
      with:
        repository: devfile/registry-support
        persist-credentials: false
        path: registry-support

    
    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: registry-repo
    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    
    - name: Check if devfile registry build is working
      run: chmod +x registry-support/build-tools/build_image.sh && registry-support/build-tools/build_image.sh registry-repo/